name: First Workflow                                               
on: push                                                  
jobs:                         
  first-job:                           
    name: Say hi                           
    runs-on: ubuntu-latest                           
    steps:                           
    - name: Print a greeting                             
      run: echo Hi from our first workflow!
      
    - name: Show ASCII greeting                             
      uses: mscoutermarsh/ascii-art-action@master   
      with:                               
        text: 'SILVIO'
        

get-posts-job:                            
    name: Get TDS posts                            
    runs-on: ubuntu-latest     
    steps:                             
      - name: Check-out the repo under $GITHUB_WORKSPACE                               
        uses: actions/checkout@v2         
                                                  
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'          
                                                  
      - name: Install Scrapy                               
        run: pip install altair
        run: pip install datapane        
 
      - name: Get TDS posts about GitHub Actions                                 
        run: python indeed.py       