name: Schedule scrap and publish

defaults:
      run:
         working-directory: .
on:
   workflow_dispatch:
   
jobs:                          
   install_packages:
      runs-on: ubuntu-latest

      steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.9
         uses: actions/setup-python@v2
         with:
           python-version: 3.9
        
       - name: Install lib bs4
         run: pip install bs4
      
       - name: Install lib selenium  
         run: pip install selenium
      
       - name: Install lib pandas  
         run: pip install pandas  
      
       - name: Install altair                              
         run: pip install altair
    
       - name: Install datapane                               
         run: pip install datapane

       - name: Install plotly-express                             
         run: pip install plotly-express  
   
   
   scrap_EML:
      runs-on: ubuntu-latest
      steps:
       - name: Scraping data EML
         run: python scrap/scrap-indeed.py 'engenheiro de machine learning'
  
        
                   
    

