







name: Schedule publish datapane                                              
on:
   workflow_dispatch:  
jobs:                          
  update_publish_datapane:                            
    name: update and publish datapane                       
    runs-on: ubuntu-latest     
    steps:                             
    - name: Check-out the repo under $GITHUB_WORKSPACE                               
      uses: actions/checkout@v2         
                                                  
    - name: Set up Python 3.8                               
      uses: actions/setup-python@v2                               
      with:                                 
        python-version: '3.8'                                                           
    - name: Install libs                          
      run: | 
           pip install altair
           pip install plotly-express
           pip install datapane     
      
    - name: running updating datapane                                
      run: python datapane_indeed.py ${{ secrets.datapane_token }}
        
