name: Schedule scrap and publish                                          
on:
   workflow_dispatch:
   
jobs:                          
  scrap_AD:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install lib bs4
      run: pip install bs4
      
    - name: Install lib selenium  
      run: pip install selenium
      
    - name: Install lib pandas  
      run: pip install pandas  
    
        
    - name: Scraping data EML
      run: |
        python scrap/scrap-indeed.py 'engenheiro de machine learning'
                   
    - name: List directory
      run: ls -la

  publish_datapane:
    needs: scrap_AD
    name: publish datapane indeed                        
    runs-on: ubuntu-latest     
    steps:                                     
                                                  
    - name: Install altair                              
      run: pip install altair
    
    - name: Install datapane                               
      run: pip install datapane

    - name: Install plotly-express                             
      run: pip install plotly-express      
      
    - name: Listar directory                            
      run: ls -la  

